import type { CardInput } from "../domain/card-schema.js";

/**
 * Seed cards for the Phase 1 prototype, drawn from the spec's initial category
 * list (Korean/Asia OAuth + deploy niche). All published so search returns them.
 * The `seedId` lets `seed.ts` upsert idempotently.
 */
export interface SeedCard extends CardInput {
  seedId: string;
}

export const SEED_CARDS: SeedCard[] = [
  {
    seedId: "seed_nextjs_spring_oauth_redirect_loop",
    title: "Next.js + Spring Security OAuth2 callback redirect loop",
    problem:
      "After Spring Security OAuth2 login the browser bounces between /login and the callback URL endlessly; the session is never established on the Next.js app.",
    environment: { frontend: "Next.js 15", backend: "Spring Boot 3", deploy: "CloudFront + API subdomain" },
    symptoms: [
      "Infinite redirect between frontend and /login/oauth2/code",
      "JSESSIONID set on the API domain but never sent back",
      "Network shows 302 loop",
    ],
    likelyCauses: [
      "Session cookie on API subdomain not shared with frontend origin",
      "SameSite=Lax blocks cross-site cookie on redirect",
      "Spring success handler redirects to a protected route",
    ],
    failedAttempts: ["Disabling CSRF only", "Changing redirect URI without fixing cookie domain"],
    verifiedFix: [
      "Issue the session/JWT as a cookie with SameSite=None; Secure on a shared parent domain",
      "Configure Spring authenticationSuccessHandler to redirect to a public frontend URL",
      "Set CORS allowedOrigins to the exact frontend origin with allowCredentials=true",
    ],
    verification: ["Login completes once with no loop", "/api/me returns the authenticated user"],
    agentHint:
      "Before touching security config, inspect whether the session cookie is actually returned on the frontend origin (SameSite/domain), not just set on the API domain.",
    sourceLinks: ["https://docs.spring.io/spring-security/reference/servlet/oauth2/login/index.html"],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_nextjs_nest_oauth_state_mismatch",
    title: "Next.js + NestJS OAuth callback state mismatch",
    problem:
      "NestJS passport OAuth callback fails with 'Unable to verify authorization request state' intermittently after deploy behind a load balancer.",
    environment: { frontend: "Next.js 15", backend: "NestJS 10", deploy: "ECS behind ALB" },
    symptoms: ["InternalOAuthError: state mismatch", "Works locally, fails in prod", "Sticky between two instances"],
    likelyCauses: [
      "OAuth state stored in in-memory session, lost across instances",
      "No shared session store behind the load balancer",
    ],
    failedAttempts: ["Retrying login", "Increasing session TTL"],
    verifiedFix: [
      "Use a shared session store (Redis) for passport OAuth state",
      "Enable sticky sessions on the ALB target group as a stopgap",
    ],
    verification: ["Repeated logins succeed across both instances"],
    agentHint: "State mismatch in multi-instance deploys almost always means the OAuth state isn't in a shared store.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_httponly_cookie_not_sent_crosssite",
    title: "HttpOnly cookie not sent on cross-site requests in production",
    problem:
      "Auth cookie is set after login but never sent on subsequent fetch() calls from the frontend to the API in production, so every request is unauthenticated.",
    environment: { frontend: "Next.js 15", backend: "NestJS / Spring", deploy: "frontend and API on different domains", browser: "Chrome, Safari" },
    symptoms: [
      "Set-Cookie visible in the login response",
      "Cookie not attached to later requests",
      "/me returns 401",
    ],
    likelyCauses: [
      "fetch missing credentials: 'include'",
      "Cookie lacks SameSite=None; Secure for cross-site",
      "CORS missing Access-Control-Allow-Credentials",
    ],
    failedAttempts: ["Reading the HttpOnly cookie from JS", "Putting the token in a query param"],
    verifiedFix: [
      "Add credentials: 'include' to all fetch calls",
      "Set cookie: HttpOnly; Secure; SameSite=None; Path=/",
      "CORS: exact origin + Access-Control-Allow-Credentials: true (no wildcard)",
    ],
    verification: ["Cookie appears in Application > Cookies", "/me authenticates", "Verified separately on Safari"],
    agentHint:
      "Before editing auth logic, check Set-Cookie attributes, CORS credentials headers, and the request credentials mode first.",
    sourceLinks: ["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie"],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_cloudfront_s3_spa_403_refresh",
    title: "CloudFront + S3 SPA returns 403/AccessDenied on route refresh",
    problem:
      "A single-page app deployed to S3 behind CloudFront works on the home page but returns 403 AccessDenied when refreshing a client-side route like /dashboard.",
    environment: { frontend: "Next.js static export / Vite SPA", deploy: "CloudFront + S3 (OAC)" },
    symptoms: ["403 on deep-link refresh", "Home route works", "S3 has no object for the sub-path"],
    likelyCauses: [
      "S3 returns 403 for missing keys (with OAC), not 404",
      "No custom error response mapping to index.html",
    ],
    failedAttempts: ["Making the bucket public", "Adding 404 -> index.html only"],
    verifiedFix: [
      "Add a CloudFront custom error response: 403 -> /index.html with 200",
      "Also map 404 -> /index.html for non-OAC setups",
      "Keep the bucket private and use Origin Access Control",
    ],
    verification: ["Refreshing /dashboard loads the SPA", "Bucket stays private"],
    agentHint: "With OAC, S3 returns 403 (not 404) for missing keys, so map the 403 error response to index.html.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_cors_credentials_wildcard",
    title: "CORS with credentials rejected when origin is wildcard",
    problem:
      "Browser blocks the response with 'Access-Control-Allow-Origin: * is not allowed when credentials mode is include'.",
    environment: { frontend: "Next.js 15", backend: "NestJS / Express" },
    symptoms: ["CORS error in console despite server sending headers", "Preflight OK but actual request blocked"],
    likelyCauses: ["Wildcard origin with credentials", "Allow-Credentials header missing"],
    failedAttempts: ["Setting Access-Control-Allow-Origin: *", "Disabling credentials"],
    verifiedFix: [
      "Reflect the exact request origin instead of '*'",
      "Set Access-Control-Allow-Credentials: true",
      "Whitelist allowed origins explicitly",
    ],
    verification: ["Credentialed fetch succeeds", "Cookie sent and received"],
    agentHint: "Credentialed CORS cannot use a wildcard origin — reflect the specific origin.",
    sourceLinks: ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_jwt_cookie_vs_header_mismatch",
    title: "JWT in HttpOnly cookie vs Authorization header mismatch",
    problem:
      "Backend expects the JWT in an Authorization: Bearer header, but the frontend stores it in an HttpOnly cookie it can't read, so all requests are unauthorized.",
    environment: { frontend: "Next.js 15", backend: "NestJS passport-jwt" },
    symptoms: ["401 on every API call", "Token present in cookie", "Guard never sees the token"],
    likelyCauses: ["JwtStrategy extracts from header, token is in cookie", "Frontend can't read HttpOnly cookie to set header"],
    failedAttempts: ["Trying to read the HttpOnly cookie in JS"],
    verifiedFix: [
      "Configure passport-jwt to extract the token from the cookie",
      "Or set the token in a readable cookie and forward it as a header (less secure)",
      "Keep one consistent transport for the token",
    ],
    verification: ["Authenticated requests pass the guard"],
    agentHint: "Pick one JWT transport (cookie or header) and make the extractor match it.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_cloudfront_stale_index_html",
    title: "CloudFront serves stale index.html after deploy",
    problem:
      "After deploying a new build, users keep getting the old app because CloudFront caches index.html and references hashed assets that no longer exist (blank page).",
    environment: { frontend: "Vite / Next static", deploy: "CloudFront + S3" },
    symptoms: ["Old app after deploy", "Blank page until hard refresh", "404 on old hashed JS"],
    likelyCauses: ["index.html cached at the edge", "No invalidation on deploy"],
    failedAttempts: ["Waiting for TTL to expire"],
    verifiedFix: [
      "Set Cache-Control: no-cache on index.html, long max-age on hashed assets",
      "Run a CloudFront invalidation for /index.html (or /*) on each deploy",
    ],
    verification: ["New deploy is visible immediately without hard refresh"],
    agentHint: "Cache hashed assets forever but never cache index.html; invalidate it on deploy.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_spring_cors_preflight_401",
    title: "Spring Boot CORS preflight returns 401 due to security filter order",
    problem:
      "OPTIONS preflight requests are rejected with 401 because Spring Security runs before CORS handling, so the browser blocks the real request.",
    environment: { backend: "Spring Boot 3 + Spring Security" },
    symptoms: ["OPTIONS returns 401", "GET/POST never reached", "CORS error in browser"],
    likelyCauses: ["Security filter intercepts preflight", "CORS not registered with Spring Security"],
    failedAttempts: ["Adding @CrossOrigin on controllers only"],
    verifiedFix: [
      "Register a CorsConfigurationSource bean and call http.cors(...) in the security chain",
      "Permit OPTIONS requests in the security config",
    ],
    verification: ["Preflight returns 200", "Subsequent request authenticates"],
    agentHint: "In Spring Security, wire CORS into the security filter chain; controller-level @CrossOrigin is not enough.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_kakao_login_redirect_uri_mismatch",
    title: "Kakao login fails with redirect_uri mismatch (KOE006)",
    problem:
      "Kakao OAuth login returns KOE006 redirect_uri mismatch in production even though it works locally.",
    environment: { frontend: "Next.js 15", backend: "NestJS", deploy: "Vercel / CloudFront" },
    symptoms: ["KOE006 error page", "Works on localhost", "Fails on the deployed domain"],
    likelyCauses: [
      "Production redirect URI not registered in Kakao developer console",
      "Trailing slash or http vs https mismatch",
    ],
    failedAttempts: ["Re-issuing the REST API key"],
    verifiedFix: [
      "Register the exact production redirect URI (scheme, host, path) in the Kakao console",
      "Ensure the URI sent matches byte-for-byte, including https and no trailing slash",
    ],
    verification: ["Kakao login succeeds in production"],
    agentHint: "redirect_uri mismatches are exact-string problems: compare the sent URI against the registered one character by character.",
    sourceLinks: ["https://developers.kakao.com/docs/latest/en/kakaologin/common"],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_env_var_not_available_runtime",
    title: "Env var not available at runtime (build-time inlining)",
    problem:
      "A NEXT_PUBLIC_/VITE_ environment variable is undefined in the browser at runtime because it was not present at build time and these vars are inlined during build.",
    environment: { frontend: "Next.js 15 / Vite", deploy: "Docker / CI build" },
    symptoms: ["process.env.X is undefined in the browser", "Works in dev, fails in built image"],
    likelyCauses: ["Public env vars are inlined at build time", "Var set only at container runtime, not build"],
    failedAttempts: ["Setting the var only in the runtime environment"],
    verifiedFix: [
      "Pass the variable as a build arg / build-time env so it is inlined",
      "For true runtime config, fetch it from a server endpoint instead of NEXT_PUBLIC_",
    ],
    verification: ["The value is present in the production browser bundle"],
    agentHint: "Public (NEXT_PUBLIC_/VITE_) vars are baked in at build time; set them during build, not just at runtime.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_naver_login_callback_email_null",
    title: "Naver login returns null email despite consent",
    problem:
      "After Naver OAuth login the profile response has no email field, so user creation fails even though the app requested the email scope.",
    environment: { frontend: "Next.js 15", backend: "NestJS", deploy: "Vercel" },
    symptoms: ["response.email is null", "User insert fails on NOT NULL email", "Works for some accounts"],
    likelyCauses: [
      "Email is an optional Naver scope the user can decline",
      "App not approved for the email field in the Naver console",
    ],
    failedAttempts: ["Assuming email is always present"],
    verifiedFix: [
      "Request and verify the email scope; handle the null case gracefully",
      "Get the email field approved in the Naver Developers console",
      "Fall back to the Naver unique id when email is absent",
    ],
    verification: ["Login works for accounts that decline email"],
    agentHint: "Treat OAuth email as optional — Naver/Kakao users can decline it; key the account on the provider id.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_github_actions_oidc_aws",
    title: "GitHub Actions can't assume AWS role (OIDC) — no permission",
    problem:
      "A deploy workflow using OIDC fails with 'Not authorized to perform sts:AssumeRoleWithWebIdentity' when assuming the AWS role.",
    environment: { deploy: "AWS", backend: "GitHub Actions" },
    symptoms: ["sts:AssumeRoleWithWebIdentity AccessDenied", "Works with static keys", "OIDC token rejected"],
    likelyCauses: [
      "Trust policy condition (sub) doesn't match the repo/branch",
      "Missing id-token: write permission in the job",
      "OIDC provider thumbprint/audience misconfigured",
    ],
    failedAttempts: ["Adding more IAM permissions to the role"],
    verifiedFix: [
      "Add permissions: id-token: write to the workflow job",
      "Set the role trust policy sub condition to repo:OWNER/REPO:ref:refs/heads/main",
      "Use aws-actions/configure-aws-credentials with role-to-assume",
    ],
    verification: ["Workflow assumes the role and deploys without static keys"],
    agentHint: "OIDC AssumeRole failures are usually the trust-policy sub condition or a missing id-token: write permission, not the role's IAM policy.",
    sourceLinks: ["https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services"],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_ec2_nginx_pm2_502",
    title: "EC2 + Nginx + PM2: 502 Bad Gateway after deploy",
    problem:
      "Nginx returns 502 Bad Gateway for the Node app running under PM2 on EC2, even though PM2 shows the process online.",
    environment: { backend: "Node + PM2", deploy: "EC2 + Nginx" },
    symptoms: ["502 Bad Gateway", "PM2 status online", "Nginx error log: connect() failed (111: Connection refused)"],
    likelyCauses: [
      "App listens on a different port than Nginx proxy_pass",
      "App bound to 127.0.0.1 vs 0.0.0.0 mismatch",
      "App crashed on boot but PM2 restarts mask it",
    ],
    failedAttempts: ["Restarting Nginx only"],
    verifiedFix: [
      "Align proxy_pass port with the app's actual listen port",
      "Confirm the app is listening (curl localhost:PORT on the box)",
      "Check pm2 logs for a boot-time crash loop",
    ],
    verification: ["curl to the upstream port succeeds; Nginx returns 200"],
    agentHint: "A 502 with 'connection refused' means Nginx reached the box but nothing is listening on the proxied port — verify the app's real port first.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_nginx_413_body_size",
    title: "Nginx returns 413 Request Entity Too Large on upload",
    problem: "File uploads above ~1MB fail with 413 before reaching the app.",
    environment: { deploy: "Nginx" },
    symptoms: ["413 Request Entity Too Large", "Small uploads work", "Request never hits the backend"],
    likelyCauses: ["Default client_max_body_size is 1MB"],
    failedAttempts: ["Increasing the app's body limit only"],
    verifiedFix: [
      "Set client_max_body_size to the desired limit in the http/server/location block",
      "Reload Nginx after the change",
    ],
    verification: ["Large upload succeeds end to end"],
    agentHint: "A 413 that never reaches the app is Nginx's client_max_body_size, not the application body parser.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_prisma_connection_pool_exhausted",
    title: "Prisma: Timed out fetching a connection from the pool",
    problem:
      "Under load the API throws 'Timed out fetching a new connection from the connection pool', especially on serverless.",
    environment: { backend: "NestJS / Next.js + Prisma", deploy: "Serverless / containers" },
    symptoms: ["P2024 connection pool timeout", "Fails under concurrency", "Too many connections on Postgres"],
    likelyCauses: [
      "Each serverless instance opens its own pool, exhausting Postgres",
      "PrismaClient instantiated per request",
      "No external pooler (PgBouncer) in front of Postgres",
    ],
    failedAttempts: ["Raising Postgres max_connections blindly"],
    verifiedFix: [
      "Reuse a single PrismaClient instance per process",
      "Put PgBouncer (or the platform pooler) in front and set connection_limit",
      "Add ?pgbouncer=true&connection_limit=1 for serverless",
    ],
    verification: ["No pool timeouts under the same load"],
    agentHint: "Pool-timeout errors on serverless are usually too many independent pools — pool externally (PgBouncer) and cap connection_limit.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_websocket_cloudfront_alb",
    title: "WebSocket connection drops behind CloudFront/ALB",
    problem:
      "WebSocket upgrades fail or disconnect after ~60s when the app is served through CloudFront and an ALB.",
    environment: { deploy: "CloudFront + ALB", backend: "Node ws / Socket.IO" },
    symptoms: ["101 then immediate close", "Disconnects at idle timeout", "Polling works, WS doesn't"],
    likelyCauses: [
      "CloudFront not forwarding Upgrade/Connection headers",
      "ALB idle timeout shorter than the heartbeat",
      "Origin protocol policy stripping the upgrade",
    ],
    failedAttempts: ["Switching transport to polling only"],
    verifiedFix: [
      "Use a CloudFront policy that forwards Upgrade and Connection headers",
      "Raise the ALB idle timeout above the WS heartbeat interval",
      "Add application-level ping/pong to keep the connection alive",
    ],
    verification: ["WebSocket stays connected past the previous timeout"],
    agentHint: "WS drops behind CDN/LB are header forwarding or idle-timeout issues — check Upgrade header forwarding and the LB idle timeout vs heartbeat.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_safari_itp_third_party_cookie",
    title: "Safari blocks third-party auth cookie (ITP)",
    problem:
      "Auth works in Chrome but Safari drops the session: the cross-site auth cookie is blocked by Intelligent Tracking Prevention.",
    environment: { frontend: "Next.js 15", backend: "NestJS", browser: "Safari" },
    symptoms: ["Logged out on every navigation in Safari", "Works in Chrome", "Cookie present then gone"],
    likelyCauses: [
      "Safari ITP blocks third-party (cross-site) cookies",
      "Auth domain differs from the app domain",
    ],
    failedAttempts: ["Only setting SameSite=None; Secure"],
    verifiedFix: [
      "Serve API and frontend under the same registrable domain (first-party)",
      "Use a same-site reverse-proxy path (/api) instead of a separate API subdomain",
      "Avoid relying on third-party cookies for auth in Safari",
    ],
    verification: ["Session persists across navigation in Safari"],
    agentHint: "If auth works in Chrome but not Safari, suspect ITP blocking third-party cookies — make the cookie first-party via a same-domain proxy path.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_docker_node_build_cache",
    title: "Docker rebuilds npm install on every code change",
    problem:
      "Every Docker build reinstalls all npm dependencies because the layer cache is invalidated by source changes, making CI slow.",
    environment: { deploy: "Docker / CI build", backend: "Node" },
    symptoms: ["npm install runs on every build", "Slow CI", "Cache never hit for deps"],
    likelyCauses: ["COPY . . before npm install invalidates the deps layer on any code change"],
    failedAttempts: ["Adding a generic .dockerignore only"],
    verifiedFix: [
      "COPY package.json and lockfile first, run npm ci, then COPY the rest",
      "Use a multi-stage build to keep the final image small",
      "Leverage BuildKit cache mounts for node_modules where available",
    ],
    verification: ["Dependency layer is cached when only source changes"],
    agentHint: "Order Dockerfile steps by change frequency: copy the lockfile and install deps before copying source so the deps layer caches.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_prisma_migrate_drift_prod",
    title: "Prisma migrate drift / failed migration in production",
    problem:
      "prisma migrate deploy fails in production with a drift error or a partially-applied migration, blocking the deploy.",
    environment: { backend: "Prisma", deploy: "CI/CD" },
    symptoms: ["P3009 migration failed", "Drift detected: schema differs from migrations", "Deploy blocked"],
    likelyCauses: [
      "A migration was applied manually / partially and left marked failed",
      "Schema changed outside of migrations",
    ],
    failedAttempts: ["Running prisma migrate reset in prod (destructive!)"],
    verifiedFix: [
      "Inspect _prisma_migrations and resolve the failed one with prisma migrate resolve",
      "Reconcile the DB to match migration history without dropping data",
      "Never use migrate reset against production",
    ],
    verification: ["migrate deploy applies cleanly on a fresh deploy"],
    agentHint: "For prod migration failures use prisma migrate resolve to mark the failed migration — never migrate reset, which drops data.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
  {
    seedId: "seed_github_actions_monorepo_cache_miss",
    title: "GitHub Actions cache miss in a monorepo",
    problem:
      "actions/cache never restores in a monorepo, so installs and builds run cold on every CI run.",
    environment: { backend: "GitHub Actions", frontend: "pnpm/npm monorepo" },
    symptoms: ["Cache not found for key", "Cold install every run", "Cache saved but never restored"],
    likelyCauses: [
      "Cache key hashes a lockfile path that doesn't match the workspace",
      "Restore keys too specific",
      "Different working-directory between save and restore",
    ],
    failedAttempts: ["Bumping the cache version manually each run"],
    verifiedFix: [
      "Key the cache on the correct lockfile glob (hashFiles('**/pnpm-lock.yaml'))",
      "Add stable restore-keys prefixes for partial hits",
      "Use the setup-node/pnpm built-in cache where possible",
    ],
    verification: ["Subsequent runs restore the cache and skip cold installs"],
    agentHint: "Monorepo cache misses are almost always a wrong hashFiles lockfile path or missing restore-keys — verify the key matches the actual lockfile.",
    sourceLinks: [],
    visibility: "public",
    status: "published",
  },
];
